## Diagrams for Course #3

In [10]:
import tensorflow as tf
x = tf.constant(3)
print x

Tensor("Const_9:0", shape=(), dtype=int32)


In [11]:
import tensorflow as tf
x = tf.constant([3, 5, 7])
print x

Tensor("Const_10:0", shape=(3,), dtype=int32)


In [4]:
import tensorflow as tf
x = tf.constant([[3, 5, 7],
                 [4, 6, 8]])
print x

Tensor("Const_3:0", shape=(2, 3), dtype=int32)


In [12]:
import tensorflow as tf
x = tf.constant([[[3, 5, 7],[4, 6, 8]],
                 [[1, 2, 3],[4, 5, 6]]
                 ])
print x

Tensor("Const_11:0", shape=(2, 2, 3), dtype=int32)


In [19]:
import tensorflow as tf
x1 = tf.constant([2, 3, 4])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2, x2, x2])
x4 = tf.stack([x3, x3])
print x1
print x2
print x3
print x4

Tensor("Const_18:0", shape=(3,), dtype=int32)
Tensor("stack_12:0", shape=(2, 3), dtype=int32)
Tensor("stack_13:0", shape=(4, 2, 3), dtype=int32)
Tensor("stack_14:0", shape=(2, 4, 2, 3), dtype=int32)


In [21]:
import tensorflow as tf
x = tf.constant([[3, 5, 7],
                 [4, 6, 8]])
y = x[:, 1]
with tf.Session() as sess:
  print y.eval()

[5 6]


In [24]:
import tensorflow as tf
x = tf.constant([[3, 5, 7],
                 [4, 6, 8]])
y = tf.reshape(x, [3, 2])
with tf.Session() as sess:
  print y.eval()

[[3 5]
 [7 4]
 [6 8]]


In [26]:
import tensorflow as tf
x = tf.constant([[3, 5, 7],
                 [4, 6, 8]])
y = tf.reshape(x, [3, 2])[1, :]
with tf.Session() as sess:
  print y.eval()

[7 4]


In [1]:
import tensorflow as tf
from tensorflow.contrib.eager.python import tfe

tfe.enable_eager_execution()

x = tf.constant([[3, 5, 7],
                 [4, 6, 8]])
y = tf.reshape(x, [3, 2])[1, :]
print y

tf.Tensor([7 4], shape=(2,), dtype=int32)


In [1]:
import tensorflow as tf
from tensorflow.contrib.eager.python import tfe

tfe.enable_eager_execution()

x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])
print (x-y)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [2]:
import tensorflow as tf

x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])
z = tf.add(x, y)

with tf.Session() as sess:
  print z.eval()

[ 4  7 10]


In [3]:
import tensorflow as tf

x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])
z = tf.add(x, y)

with tf.Session() as sess:
  print sess.run(z)

[ 4  7 10]


In [9]:
import tensorflow as tf

x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])
z1 = x + y
z2 = x * y
z3 = z2 - z1

with tf.Session() as sess:
  a1, a3 = sess.run([z1, z3])
  print a1
  print a3

[ 4  7 10]
[-1  3 11]


In [1]:
import tensorflow as tf

x = tf.constant([3, 5, 7], name="x")
y = tf.constant([1, 2, 3], name="y")
z1 = tf.add(x, y, name="z1")
z2 = x * y
z3 = z2 - z1

with tf.Session() as sess:
  with tf.summary.FileWriter('summaries', sess.graph) as writer:
      a1, a3 = sess.run([z1, z3])

In [15]:
!ls summaries

events.out.tfevents.1517032067.e7cbb0325e48


In [16]:
from google.datalab.ml import TensorBoard
TensorBoard().start('./summaries')

TensorBoard was started successfully with pid 13045. Click here to access it.

13045

In [3]:
from google.datalab.ml import TensorBoard
TensorBoard().stop(13045)
print 'stopped TensorBoard'

stopped TensorBoard


In [3]:
import tensorflow as tf

def forward_pass(w, x):
    return tf.matmul(w, x)

def train_loop(x, niter=5):
  with tf.variable_scope("model", reuse=tf.AUTO_REUSE):
    w = tf.get_variable("weights", 
                    shape=(1,2),  # 1 x 2 matrix
                    initializer=tf.truncated_normal_initializer(),
                    trainable=True)
  preds = []
  for k in xrange(niter):
    preds.append(forward_pass(w, x))
    w = w + 0.1 # "gradient update"
  return preds

with tf.Session() as sess:
  preds = train_loop(tf.constant([[3.2, 5.1, 7.2],[4.3, 6.2, 8.3]])) # 2 x 3 matrix
  tf.global_variables_initializer().run()
  for i in xrange(len(preds)):
      print "{}:{}".format( i, preds[i].eval() )

0:[[-0.53224635 -1.4080029  -2.3759441 ]]
1:[[ 0.21775389 -0.27800274 -0.82594395]]
2:[[0.96775365 0.8519969  0.72405624]]
3:[[1.7177541 1.981997  2.2740564]]
4:[[2.4677541 3.1119976 3.8240576]]
